Added support for 2.0.0 beta version of UltimateClaims
RonanPlugins/BetterRTP pull request #175
Opened 2023-09-02 19:45 UTC by Styro457

In the new beta version of UltimateClaims from their github they changed the package name from com.songoda.ultimateclaims to com.craftaro.ultimateclaims. I added a check so that the plugin works with both the old and the new versions.

2023-10-06 08:51 UTC, TechnicallyCoded commented
Class and method resolution should probably happens at startup and not runtime but the rest of the code already does this, so 🤷

2023-10-06 08:53 UTC, TechnicallyCoded requested changes
Please update the method comment to reflect the changes

2023-10-07 04:20 UTC, SuperRonanCraft commented
Technically added support for this, thank you!

2023-10-07 04:20 UTC, closed without merging

2023-10-27 09:43 UTC, Styro457 commented
I do not see support for this. The plugin still gives this error when using the beta version of UltimateClaims where they changed the package names:

[09:32:35 WARN]: java.lang.ClassNotFoundException: com.songoda.ultimateclaims.UltimateClaims
[09:32:35 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183)
[09:32:35 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150)
[09:32:35 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
[09:32:35 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[09:32:35 WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[09:32:35 WARN]:        at BetterRTP.jar//me.SuperRonanCraft.BetterRTP.references.depends.regionPlugins.RTP_UltimateClaims.check(RTP_UltimateClaims.java:20)
[09:32:35 WARN]:        at BetterRTP.jar//me.SuperRonanCraft.BetterRTP.player.rtp.RTPPluginValidation.checkLocation(RTPPluginValidation.java:14)
[09:32:35 WARN]:        at BetterRTP.jar//me.SuperRonanCraft.BetterRTP.player.rtp.RTPPlayer.checkDepends(RTPPlayer.java:121)
[09:32:35 WARN]:        at BetterRTP.jar//me.SuperRonanCraft.BetterRTP.player.rtp.RTPPlayer.attempt(RTPPlayer.java:89)
[09:32:35 WARN]:        at BetterRTP.jar//me.SuperRonanCraft.BetterRTP.player.rtp.RTPPlayer.lambda$randomlyTeleport$0(RTPPlayer.java:71)
[09:32:35 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
[09:32:35 WARN]:        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[09:32:35 WARN]:        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
[09:32:35 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftWorld.lambda$getChunkAtAsync$16(CraftWorld.java:2420)
[09:32:35 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[09:32:35 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[09:32:35 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[09:32:35 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1338)
[09:32:35 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[09:32:35 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[09:32:35 WARN]:        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1315)
[09:32:35 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1308)
[09:32:35 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[09:32:35 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1385)
[09:32:35 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1170)
[09:32:35 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[09:32:35 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)